### PR TITLE
Fixing Various Issues

### PR DESCRIPTION
**Pull request by DanNsk**
I think i fixed a couple of issues (ubx_get_val not-working on f9p, high resolution navigation message scaling, some predefined message classes not working). 

- added configuration for UBX-MON-VER  and UBX-CFG-MSG
- worker thread to read UBX and NMEA messages asynchronously.
- added ubx_set_val 
- added variable length string handler (to be able to handle messages like  UBX-MON-VER)
- added set_auto_msg - to be able to configure GPS automatic message generation (as an example -             gps.set_auto_msg('NAV','PVT', 1) - will auto-generate message UBX-NAV-PVT on every navigation cycle, so instead of polling on every call of we're going to use automatically generated message data, which will make out program main thread more or less asynchronous)
- made result scaling , and message polling generic functions

I also tried to keep class interface exactly the same as you had

### CODE REVIEW

**Comment by edspark** [comment]
This is awesome, I'll take a look at this as soon as I can.

**Comment by LarsJaeger** [comment]
It's a shame that this pull request has still not been accepted. I've even written a mail about half a year ago. They said they would look into this, but they did not. Without these fixes some important core features are still not working, I am really disappointed.

**Comment by timwedde** [comment]
I'm also waiting for this to be accepted, it's kind of a pain to have to integrate these fixes manually by shipping a custom fork of this library.

**Comment by timwedde** [comment]
God bless, thanks a bunch!

**Comment by edspark** [comment]
Aye indeed, it's been a long time coming. An excellent pull request - I do regret the long wait but if you're out there @DanNsk - Thanks!

**Pull request merged**
